name: todo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: ^10.2.9
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  rich_editor: ^0.0.5
  flutter_inappwebview: ^5.3.2
  # multi_image_picker2: ^5.0.02
  get: ^4.6.1
  json_annotation: ^4.4.0
  test: ^1.19.5
  cloud_firestore: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^6.1.5 # For serializing objects to JSON
  flutter_lints: ^1.0.0 # Add this line if you want to use the lint rules provided by the package.

flutter: # This line is required.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
